site_name: python-api-tesing
docs_dir: docs
theme:
  name: material
markdown_extensions:
- tables
- admonition
- toc
- pymdownx.superfences
nav:
- Documentation technique: documentation.md
- Architecture: architecture.md
- Diagramme de structure: diagramme.md
- Comparaison architectures: comparaison.md
- Détection & recommandations: detection.md
- Racine: root.md
- 2020_100_examples: 2020_100_examples.md
- bazi: bazi.md
- book_scraper: book_scraper.md
- buildbot/hello-world: buildbot_hello-world.md
- buildbot/hello-world/hello: buildbot_hello-world_hello.md
- flask: flask.md
- flask/api_demo: flask_api_demo.md
- flask/api_demo/migrations: flask_api_demo_migrations.md
- flask/api_demo/migrations/versions: flask_api_demo_migrations_versions.md
- flask/api_demo/resources: flask_api_demo_resources.md
- flask/filemanager: flask_filemanager.md
- flask/filemanager/migrations: flask_filemanager_migrations.md
- flask/filemanager/migrations/versions: flask_filemanager_migrations_versions.md
- flask/filemanager/resources: flask_filemanager_resources.md
- flask/flask_web_service/Chapter01: flask_flask_web_service_Chapter01.md
- flask/flask_web_service/Chapter02: flask_flask_web_service_Chapter02.md
- flask/flask_web_service/Chapter03: flask_flask_web_service_Chapter03.md
- flask/flask_web_service/Chapter04: flask_flask_web_service_Chapter04.md
- flask/flask_web_service/Chapter04-get: flask_flask_web_service_Chapter04-get.md
- flask/flask_web_service/Chapter04-post: flask_flask_web_service_Chapter04-post.md
- flask/flask_web_service/Chapter05: flask_flask_web_service_Chapter05.md
- flask/flask_web_service/Chapter06: flask_flask_web_service_Chapter06.md
- flask/flask_web_service/Chapter07: flask_flask_web_service_Chapter07.md
- flask/flask_web_service/Chapter08: flask_flask_web_service_Chapter08.md
- flask/flask_web_service/Chapter09: flask_flask_web_service_Chapter09.md
- flask/flask_web_service/Chapter09/static/js: flask_flask_web_service_Chapter09_static_js.md
- flask/flask_web_service/Chapter10: flask_flask_web_service_Chapter10.md
- flask/flask_web_service/Chapter10/static/js: flask_flask_web_service_Chapter10_static_js.md
- flask/flask_web_service/Chapter11: flask_flask_web_service_Chapter11.md
- flask/flask_web_service/Chapter11/static/js: flask_flask_web_service_Chapter11_static_js.md
- flask/waiter_caller_mongo: flask_waiter_caller_mongo.md
- flask/waiter_caller_mongo/static/js: flask_waiter_caller_mongo_static_js.md
- flask/waiter_caller_postgresql: flask_waiter_caller_postgresql.md
- flask/waiter_caller_postgresql/static/js: flask_waiter_caller_postgresql_static_js.md
- install: install.md
- opencv_crash_deep_learning/ch01: opencv_crash_deep_learning_ch01.md
- opencv_crash_deep_learning/ch02: opencv_crash_deep_learning_ch02.md
- other: other.md
- pandas/excel_demo: pandas_excel_demo.md
- pandas/excel_demo/xls: pandas_excel_demo_xls.md
- pandas/python_data_analyse_crash_course/1: pandas_python_data_analyse_crash_course_1.md
- pandas/python_data_analyse_crash_course/2: pandas_python_data_analyse_crash_course_2.md
- pandas/python_data_analyse_crash_course/3: pandas_python_data_analyse_crash_course_3.md
- practices: practices.md
- practices/cv: practices_cv.md
- practices/keras: practices_keras.md
- practices/pandas: practices_pandas.md
- practices/pillow: practices_pillow.md
- practices/tk: practices_tk.md
- practices/ts: practices_ts.md
- python-automation-cook/ch3: python-automation-cook_ch3.md
- python3.7quick: python3.7quick.md
- python3_libraries/_dubbo: python3_libraries__dubbo.md
- python3_libraries/asyncio: python3_libraries_asyncio.md
- python3_libraries/collections: python3_libraries_collections.md
- python3_libraries/daemon: python3_libraries_daemon.md
- python3_libraries/face_recognition: python3_libraries_face_recognition.md
- python3_libraries/matplotlib/examples/1: python3_libraries_matplotlib_examples_1.md
- python3_libraries/matplotlib/examples/2: python3_libraries_matplotlib_examples_2.md
- python3_libraries/numpy/Chapter1: python3_libraries_numpy_Chapter1.md
- python3_libraries/numpy/Chapter10: python3_libraries_numpy_Chapter10.md
- python3_libraries/numpy/Chapter11: python3_libraries_numpy_Chapter11.md
- python3_libraries/numpy/Chapter2: python3_libraries_numpy_Chapter2.md
- python3_libraries/numpy/Chapter3: python3_libraries_numpy_Chapter3.md
- python3_libraries/numpy/Chapter4: python3_libraries_numpy_Chapter4.md
- python3_libraries/numpy/Chapter5: python3_libraries_numpy_Chapter5.md
- python3_libraries/numpy/Chapter6: python3_libraries_numpy_Chapter6.md
- python3_libraries/numpy/Chapter7: python3_libraries_numpy_Chapter7.md
- python3_libraries/numpy/Chapter8: python3_libraries_numpy_Chapter8.md
- python3_libraries/numpy/Chapter9: python3_libraries_numpy_Chapter9.md
- python3_libraries/opencv/opencv3by_example/Chapter01: python3_libraries_opencv_opencv3by_example_Chapter01.md
- python3_libraries/opencv/opencv3by_example/Chapter02: python3_libraries_opencv_opencv3by_example_Chapter02.md
- python3_libraries/opencv/opencv3by_example/Chapter03: python3_libraries_opencv_opencv3by_example_Chapter03.md
- python3_libraries/opencv/opencv3by_example/Chapter04: python3_libraries_opencv_opencv3by_example_Chapter04.md
- python3_libraries/opencv/opencv3by_example/Chapter05: python3_libraries_opencv_opencv3by_example_Chapter05.md
- python3_libraries/opencv/opencv3by_example/Chapter06: python3_libraries_opencv_opencv3by_example_Chapter06.md
- python3_libraries/opencv/opencv3by_example/Chapter07: python3_libraries_opencv_opencv3by_example_Chapter07.md
- python3_libraries/opencv/opencv3by_example/Chapter08: python3_libraries_opencv_opencv3by_example_Chapter08.md
- python3_libraries/opencv/opencv3by_example/Chapter09: python3_libraries_opencv_opencv3by_example_Chapter09.md
- python3_libraries/opencv/opencv3by_example/Chapter10: python3_libraries_opencv_opencv3by_example_Chapter10.md
- python3_libraries/opencv/opencv3by_example/Chapter11: python3_libraries_opencv_opencv3by_example_Chapter11.md
- python3_libraries/os.path: python3_libraries_os.path.md
- python3_libraries/pathlib: python3_libraries_pathlib.md
- python3_libraries/pexpect: python3_libraries_pexpect.md
- python3_libraries/pillow: python3_libraries_pillow.md
- python3_libraries/pytesseract: python3_libraries_pytesseract.md
- python3_libraries/pytest_testing/appendices/outcomes: python3_libraries_pytest_testing_appendices_outcomes.md
- python3_libraries/pytest_testing/appendices/packaging/some_package_proj_v2: python3_libraries_pytest_testing_appendices_packaging_some_package_proj_v2.md
- python3_libraries/pytest_testing/appendices/xdist: python3_libraries_pytest_testing_appendices_xdist.md
- python3_libraries/pytest_testing/appendices/xunit: python3_libraries_pytest_testing_appendices_xunit.md
- python3_libraries/pytest_testing/ch1/tasks: python3_libraries_pytest_testing_ch1_tasks.md
- python3_libraries/pytest_testing/ch2/tasks_proj/tests/func: python3_libraries_pytest_testing_ch2_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch2/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch2_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch3: python3_libraries_pytest_testing_ch3.md
- python3_libraries/pytest_testing/ch3/a/tasks_proj/tests: python3_libraries_pytest_testing_ch3_a_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch3/a/tasks_proj/tests/func: python3_libraries_pytest_testing_ch3_a_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch3/a/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch3_a_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch3/b/tasks_proj/tests: python3_libraries_pytest_testing_ch3_b_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch3/b/tasks_proj/tests/func: python3_libraries_pytest_testing_ch3_b_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch3/b/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch3_b_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch3/c/tasks_proj/tests: python3_libraries_pytest_testing_ch3_c_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch3/c/tasks_proj/tests/func: python3_libraries_pytest_testing_ch3_c_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch3/c/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch3_c_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch4: python3_libraries_pytest_testing_ch4.md
- python3_libraries/pytest_testing/ch4/authors: python3_libraries_pytest_testing_ch4_authors.md
- python3_libraries/pytest_testing/ch4/cache: python3_libraries_pytest_testing_ch4_cache.md
- python3_libraries/pytest_testing/ch4/cap: python3_libraries_pytest_testing_ch4_cap.md
- python3_libraries/pytest_testing/ch4/dt/1: python3_libraries_pytest_testing_ch4_dt_1.md
- python3_libraries/pytest_testing/ch4/dt/2: python3_libraries_pytest_testing_ch4_dt_2.md
- python3_libraries/pytest_testing/ch4/dt/3: python3_libraries_pytest_testing_ch4_dt_3.md
- python3_libraries/pytest_testing/ch4/monkey: python3_libraries_pytest_testing_ch4_monkey.md
- python3_libraries/pytest_testing/ch4/pytestconfig: python3_libraries_pytest_testing_ch4_pytestconfig.md
- python3_libraries/pytest_testing/ch5/a/tasks_proj/tests: python3_libraries_pytest_testing_ch5_a_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch5/a/tasks_proj/tests/func: python3_libraries_pytest_testing_ch5_a_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch5/a/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch5_a_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch5/b/tasks_proj/tests: python3_libraries_pytest_testing_ch5_b_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch5/b/tasks_proj/tests/func: python3_libraries_pytest_testing_ch5_b_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch5/b/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch5_b_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch5/c/tasks_proj/tests: python3_libraries_pytest_testing_ch5_c_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch5/c/tasks_proj/tests/func: python3_libraries_pytest_testing_ch5_c_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch5/c/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch5_c_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch5/pytest-nice: python3_libraries_pytest_testing_ch5_pytest-nice.md
- python3_libraries/pytest_testing/ch5/pytest-nice/tests: python3_libraries_pytest_testing_ch5_pytest-nice_tests.md
- python3_libraries/pytest_testing/ch6/a/tasks_proj/tests: python3_libraries_pytest_testing_ch6_a_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch6/a/tasks_proj/tests/func: python3_libraries_pytest_testing_ch6_a_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch6/a/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch6_a_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch6/b/tasks_proj/tests: python3_libraries_pytest_testing_ch6_b_tasks_proj_tests.md
- python3_libraries/pytest_testing/ch6/b/tasks_proj/tests/func: python3_libraries_pytest_testing_ch6_b_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/ch6/b/tasks_proj/tests/unit: python3_libraries_pytest_testing_ch6_b_tasks_proj_tests_unit.md
- python3_libraries/pytest_testing/ch7/tasks_proj_v2: python3_libraries_pytest_testing_ch7_tasks_proj_v2.md
- python3_libraries/pytest_testing/ch7/tasks_proj_v2/src/tasks: python3_libraries_pytest_testing_ch7_tasks_proj_v2_src_tasks.md
- python3_libraries/pytest_testing/ch7/tasks_proj_v2/tests: python3_libraries_pytest_testing_ch7_tasks_proj_v2_tests.md
- python3_libraries/pytest_testing/ch7/tasks_proj_v2/tests/func: python3_libraries_pytest_testing_ch7_tasks_proj_v2_tests_func.md
- python3_libraries/pytest_testing/ch7/tasks_proj_v2/tests/unit: python3_libraries_pytest_testing_ch7_tasks_proj_v2_tests_unit.md
- python3_libraries/pytest_testing/ch7/unittest: python3_libraries_pytest_testing_ch7_unittest.md
- python3_libraries/pytest_testing/tasks_proj: python3_libraries_pytest_testing_tasks_proj.md
- python3_libraries/pytest_testing/tasks_proj/src/tasks: python3_libraries_pytest_testing_tasks_proj_src_tasks.md
- python3_libraries/pytest_testing/tasks_proj/tests/func: python3_libraries_pytest_testing_tasks_proj_tests_func.md
- python3_libraries/pytest_testing/tasks_proj/tests/unit: python3_libraries_pytest_testing_tasks_proj_tests_unit.md
- python3_libraries/string: python3_libraries_string.md
- python3_libraries/time: python3_libraries_time.md
- python_crash_tutorial/Ch1: python_crash_tutorial_Ch1.md
- python_crash_tutorial/Ch2: python_crash_tutorial_Ch2.md
- python_crash_tutorial/Ch3: python_crash_tutorial_Ch3.md
- python_crash_tutorial/Ch4: python_crash_tutorial_Ch4.md
- python_crash_tutorial/Ch5: python_crash_tutorial_Ch5.md
- python_crash_tutorial/examples/examples/HowTo: python_crash_tutorial_examples_examples_HowTo.md
- python_crash_tutorial/examples/examples/InText: python_crash_tutorial_examples_examples_InText.md
- selenium_examples/ch5: selenium_examples_ch5.md
- selenium_examples/ch6: selenium_examples_ch6.md
- shouxiang: shouxiang.md
- tools: tools.md
- weeks/2018_06_01: weeks_2018_06_01.md
- weeks/2018_06_06: weeks_2018_06_06.md
- weeks/2018_06_07: weeks_2018_06_07.md
- weeks/2018_06_12: weeks_2018_06_12.md
- weeks/2018_06_15: weeks_2018_06_15.md
repo_url: https://github.com/china-testing/python-api-tesing.git
