site_name: ai_doc_gen_8vcrw04f
docs_dir: docs
theme:
  name: material
markdown_extensions:
- tables
- admonition
- toc
- pymdownx.superfences
nav:
- Architecture: architecture.md
- Diagramme de structure: diagramme.md
- Comparaison des architectures: comparaison.md
- Détection & recommandations: detection.md
- Racine: root.md
- src: src.md
repo_url: https://github.com/Alpha94/Calculatrice.git
