site_name: pipeline-calculatrice-Jenkins
docs_dir: docs
theme:
  name: material
markdown_extensions:
- tables
- admonition
- toc
- pymdownx.superfences
nav:
- Documentation technique: documentation.md
- Architecture: architecture.md
- Diagramme de structure: diagramme.md
- Comparaison architectures: comparaison.md
- Détection & recommandations: detection.md
- sources: sources.md
repo_url: https://github.com/DataScientest/pipeline-calculatrice-Jenkins.git
